inherit_gem:
  spbtv_code_style: .rubocop.yml

Style/AccessorMethodName:
  Exclude:
    - 'lib/might/result.rb'
#
# Configuration parameters: Exclude.
Style/Documentation:
  Exclude:
    - 'spec/**/*.rb'
