---
language: ruby
rvm:
- 2.2.5
- 2.3.1
script:
- bundle exec rake spec
- bundle exec rubocop --fail-level C
gemfile:
- gemfiles/rails_4.2.7_ransack_1.6.6.gemfile
- gemfiles/rails_4.2.7_ransack_1.8.2.gemfile
- gemfiles/rails_5.0.0_ransack_1.6.6.gemfile
- gemfiles/rails_5.0.0_ransack_1.8.2.gemfile
