sudo: false
language: ruby
rvm:
  - 2.2.2
  - 2.2.3
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
before_install: gem install bundler -v 1.10.6
script:
  - bundle exec rake
  - bundle exec rubocop --fail-level C
